import turtle as t
t.pensize(3)
t.pencolor("blue")
t.circle(50)
t.rt(90)
t.pencolor("goldenrod")
t.circle(50)
t.circle(50, extent = 180)
t.rt(90)
t.pencolor("black")
t.pu()
t.fd(10)
t.pd()
t.circle(50)
t.rt(90)
t.pencolor("green")
t.circle(50)
t.circle(50, extent = 180)
t.pencolor("firebrick")
t.rt(90)
t.pu()
t.fd(10)
t.pd()
t.circle(50)